libhugetlbfs: install tests to -dev package
Some binaries depends on .so libraries in -dev package to run, so
install them to -dev package.

Don't try to split debug symbols to avoid do_package issue. Log:
ERROR: debugedit failed with exit code -11 (/usr/lib/libhugetlbfs/tests/obj32/zero_filesize_segment')
ERROR: Function failed: split_and_strip_files
ERROR: libhugetlbfs_git.bb, do_package) failed with exit code '1'

Signed-off-by: Zongchun Yu <b40527@freescale.com>
Signed-off-by: Zhenhua Luo <zhenhua.luo@freescale.com>
Signed-off-by: Ting Liu <b28495@freescale.com>
Change-Id: I1e5d0684e665e9e85e0fc58f99f21a1399cd4e4b
Reviewed-on: http://git.am.freescale.net:8181/1671
Reviewed-by: Liu Ting-B28495 <ting.liu@freescale.com>
Tested-by: Liu Ting-B28495 <ting.liu@freescale.com>