openstack-demo: extend the content of FILES_openstack-demo
Fix following error due to empty content in openstack-demo binary package..
    ERROR: openstack-demo not found in the base feeds (t2080qds ppce6500 powerpc noarch any all).

Signed-off-by: Zhenhua Luo <zhenhua.luo@freescale.com>
Change-Id: Iec6445b6d8cf6ca05c7ebc8fc1edcd4dac7a90e3
Reviewed-on: http://git.am.freescale.net:8181/24004