valgrind: Disable MPI support.
In upstream Poky, Valgrind is already configured with '--without-mpicc'.

We also need to disable MPI support, to make sure that the host's mpicc
is not used along the way, which messes libmpiwrap-ppc64-linux.so, by
compiling it for the host's architecture, instead of PowerPC. This, in
turn, leads to the following error:

ERROR: objcopy failed with exit code 1 (cmd was 'powerpc64-fsl_networking-linux-objcopy' --only-keep-debug '/home/para/Desktop/sdk-v1.5.x/build_t4240qds-64b_release/tmp/work/ppc64e6500-fsl_networking-linux/valgrind/3.9.0-r0/package/usr/lib64/valgrind/libmpiwrap-ppc64-linux.so' '/home/para/Desktop/sdk-v1.5.x/build_t4240qds-64b_release/tmp/work/ppc64e6500-fsl_networking-linux/valgrind/3.9.0-r0/package/usr/lib64/valgrind/.debug/libmpiwrap-ppc64-linux.so')
ERROR: Function failed: split_and_strip_files

Signed-off-by: Cosmin Paraschiv <cosmin.paraschiv@freescale.com>
Change-Id: I95a0df3b9c89fab7fceda125a2429498697db4e3
Reviewed-on: http://git.am.freescale.net:8181/7469
Reviewed-by: Zhenhua Luo <zhenhua.luo@freescale.com>
Tested-by: Zhenhua Luo <zhenhua.luo@freescale.com>