Revert "libhugetlbfs: fix QA issue for 64bit targets build"
This reverts commit d783024603cdc0f1fe6c3146b09db8161d781876.
ERROR: debugedit failed with exit code -11 (cmd was '/home/yocto/sdk-devel/build_p4080ds_release/tmp/sysroots/x86_64-linux/usr/lib/rpm/bin/debugedit' -b '/home/yocto/sdk-devel/build_p4080ds_release/tmp/work/ppce500mc-fsl_networking-linux' -d '/usr/src/debug' -i -l '/home/yocto/sdk-devel/build_p4080ds_release/tmp/work/ppce500mc-fsl_networking-linux/libhugetlbfs/git-r7/debugsources.list' '/home/yocto/sdk-devel/build_p4080ds_release/tmp/work/ppce500mc-fsl_networking-linux/libhugetlbfs/git-r7/package/usr/lib/libhugetlbfs/tests/obj32/zero_filesize_segment')
ERROR: Function failed: split_and_strip_files
ERROR: Logfile of failure stored in: /home/yocto/sdk-devel/build_p4080ds_release/tmp/work/ppce500mc-fsl_networking-linux/libhugetlbfs/git-r7/temp/log.do_package.9744
ERROR: Task 10 (/home/yocto/sdk-devel/poky/../meta-fsl-networking/recipes-tools/libhugetlbfs/libhugetlbfs_git.bb, do_package) failed with exit code '1'