Revert "libhugetlbfs:add "lib(*.so)" and "tests" directory of libhugetlbfs packet into RFS"
This reverts commit e880a75e8422ce335b8f4dae73bb4eea1b46d19c.
Fix following error:
    ERROR: debugedit failed with exit code -11 (cmd was '/home/yocto/sdk-devel/build_p4080ds_release/tmp/sysroots/x86_64-linux/usr/li
    ERROR: Function failed: split_and_strip_files
    ERROR: Logfile of failure stored in: /home/yocto/sdk-devel/build_p4080ds_release/tmp/work/ppce500mc-fsl_networking-linux/libhuget
    ERROR: Task 10 (/home/yocto/sdk-devel/poky/../meta-fsl-networking/recipes-tools/libhugetlbfs/libhugetlbfs_git.bb, do_package) fai