cryptodev: lock down the working SHA
AUTOREV of cryptodev breaks the openssl build, so lock down the working commit.

Error log of openssl build:
In file included from eng_cryptodev.c:57:0:
/local/build/sdk-devel/build_p4080ds_release/tmp/sysroots/p4080ds/usr/include/crypto/cryptodev.h:253:15: error: field 'curve_type' has incomplete type
  enum curve_t curve_type; /* 0 == Discrete Log,
               ^

Signed-off-by: Zhenhua Luo <zhenhua.luo@freescale.com>
Change-Id: I102296407a3ba22f62f7febdaf171f019627c84e
Reviewed-on: http://git.am.freescale.net:8181/10013