move u-boot bb in the right folder
1. move u-boot bb out of recipes-append
2. remove u-boot from IMAGE_INSTALL of fsl-image-minimal to fix below
   parse error
   ERROR: Nothing RPROVIDES 'u-boot' (but /home/yocto/workspace/meta-fsl-networking/images/fsl-image-core.bb
   RDEPENDS on or otherwise requires it)

Signed-off-by: Zhenhua Luo <zhenhua.luo@freescale.com>